[grpc]
address = "0.0.0.0:18000"

[grpc.services.storageprovider]
driver = "nextcloud"
mount_path = "/nc"
mount_id = "123e4567-e89b-12d3-a456-426655440000"
expose_data_server = true
data_server_url = "http://nexcloud/data"

[grpc.services.storageprovider.drivers.nextcloud]
end_point = "http://nextcloud/app/sciencemesh/do.php"

[http]
address = "0.0.0.0:18001"
