[grpc]
address = "0.0.0.0:18000"

[grpc.services.storageprovider]
driver = "s3ng"
mount_path = "/oc"
mount_id = "123e4567-e89b-12d3-a456-426655440000"
expose_data_server = true
data_server_url = "http://revad-services:11001/data"

[http]
address = "0.0.0.0:18001"
