[shared]
gatewaysvc = "localhost:19000"
# gatewaycertfile = "/etc/revad/tls/revad1.crt"

# [registry]
# driver = "static"
#
# [registry.static]
# services = ["authprovider","userprovider"]
#
# [registry.static.authprovider]
# bearer = ["localhost:0123"]
# basic = ["localhost:1234"]
# publiclink = ["localhost:9876"]

[grpc]
address = "localhost:19000"
# certfile = "/etc/revad/tls/revad1.crt"
# keyfile = "/etc/revad/tls/revad1.key"

[grpc.services.gateway]
authregistrysvc = "localhost:19000"
appprovidersvc = "localhost:19000"
appregistry = "localhost:19000"
storageregistrysvc = "localhost:19000"
preferencessvc = "localhost:19000"
userprovidersvc = "localhost:19000"
usershareprovidersvc = "localhost:19000"
publicshareprovidersvc = "localhost:19000"
ocmcoresvc = "localhost:19000"
ocmshareprovidersvc = "localhost:19000"
ocminvitemanagersvc = "localhost:19000"
ocmproviderauthorizersvc = "localhost:19000"
commit_share_to_storage_grant = false
datagateway = "http://localhost/data"
transfer_expires = 6 # give it a moment

[grpc.services.authregistry]
driver = "static"

[grpc.services.authregistry.drivers.static.rules]
basic = "localhost:19000"

[grpc.services.storageregistry]
driver = "static"

[grpc.services.storageregistry.drivers.static]
home_provider = "/home"

[grpc.services.storageregistry.drivers.static.rules]
"/home" = {"address" = "localhost:19000"}
"123e4567-e89b-12d3-a456-426655440000" = {"address" = "localhost:19000"}

[grpc.services.usershareprovider]
driver = "memory"

[grpc.services.ocmcore]
driver = "nextcloud"

# Note that ocmcore and ocmshareprovider should use the same config
[grpc.services.ocmcore.drivers.nextcloud]
endpoint = "https://nc1.docker/index.php/apps/sciencemesh/"
shared_secret = "should-match-nc-revaSharedSecret"
mock_http = false

[grpc.services.ocmcore.drivers.json]
file = "/var/tmp/reva/shares_server_1.json"

[grpc.services.ocminvitemanager]
driver = "json"

[grpc.services.ocmshareprovider]
driver = "nextcloud"

# Note that ocmcore and ocmshareprovider should use the same config
[grpc.services.ocmshareprovider.drivers.nextcloud]
endpoint = "https://nc1.docker/index.php/apps/sciencemesh/"
shared_secret = "should-match-nc-revaSharedSecret"
mock_http = false

[grpc.services.ocmproviderauthorizer]
driver = "json"
verify_request_hostname = true

[grpc.services.ocmproviderauthorizer.drivers.json]
providers = "providers.demo.json"

[grpc.services.publicshareprovider]
driver = "memory"

[grpc.services.appprovider]
driver = "demo"
iopsecret = "testsecret"
wopiurl = "http://localhost:8880/"
wopibridgeurl = "http://localhost:8000/wopib"

[grpc.services.appregistry]
driver = "static"

[grpc.services.appregistry.static.rules]
"text/plain" = "localhost:19000"
"text/markdown" = "localhost:19000"
"application/compressed-markdown" = "localhost:19000"
"application/vnd.oasis.opendocument.text" = "localhost:19000"
"application/vnd.oasis.opendocument.spreadsheet" = "localhost:19000"
"application/vnd.oasis.opendocument.presentation" = "localhost:19000"

[grpc.services.storageprovider]
driver = "nextcloud"

[grpc.services.storageprovider.mimetypes]
".zmd" = "application/compressed-markdown"

[grpc.services.storageprovider.drivers.nextcloud]
endpoint = "https://nc1.docker/index.php/apps/sciencemesh/"
shared_secret = "should-match-nc-revaSharedSecret"
mock_http = false

[grpc.services.authprovider]
auth_manager = "nextcloud"

[grpc.services.authprovider.auth_managers.nextcloud]
endpoint = "https://nc1.docker/index.php/apps/sciencemesh/"
shared_secret = "should-match-nc-revaSharedSecret"
mock_http = false

[grpc.services.userprovider]
driver = "nextcloud"

[grpc.services.userprovider.drivers.nextcloud]
endpoint = "https://nc1.docker/index.php/apps/sciencemesh/"
shared_secret = "should-match-nc-revaSharedSecret"
mock_http = false

[http]
enabled_services = ["ocmd"]
enabled_middlewares = ["providerauthorizer", "cors"]
address = "0.0.0.0:443"
certfile = "/etc/letsencrypt/live/mesh.pondersource.org/fullchain.pem"
keyfile = "/etc/letsencrypt/live/mesh.pondersource.org/privkey.pem"

[http.services.dataprovider]
driver = "localhome"

[http.services.prometheus]
[http.services.sysinfo]

[http.services.dataprovider.drivers.localhome]
user_layout = "{{.Username}}"

[http.services.ocmd]
prefix = ""

[http.services.ocmd.config]
host = "mesh.pondersource.org"
provider = "pondersource"

[http.middlewares.providerauthorizer]
driver = "json"

[http.middlewares.providerauthorizer.drivers.json]
providers = "providers.demo.json"

[http.services.ocs]
prefix = "ocs"

[http.services.ocdav]
prefix = "ocdav"

[http.middlewares.cors]
